- name: my first role
  hosts: target
  become: true

  roles:
    # - name: common/locale
    #   tags: "locale"
    - name: common/packages
      tags: "packages"
    - name: common/sdkman
      tags: "sdkman"
    - name: common/java
      tags: "java"
    - name: common/embulk
      tags: "embulk"

  post_tasks:
    - name: Restart target nodes
      shell: echo "enable server myapplb/{{ inventory_hostname }}"