# Install SDKMAN if not uninstalled

- name: Download SDKMAN
  get_url:
    url: https://get.sdkman.io
    dest: '{{ sdkman_tmp_dir }}/sdkman_script'
    owner: '{{ sdkman_user }}'
    group: '{{ sdkman_group }}'
    validate_certs: '{{ sdkman_validate_ssl }}'
- name: Run SDKMAN script
  environment:
    SDKMAN_DIR: '{{ sdkman_dir }}'
  command: /bin/bash {{ sdkman_tmp_dir }}/sdkman_script
  args:
    creates: '{{ sdkman_dir }}/bin/sdkman-init.sh'
  notify: Cleanup SDKMAN script

  when: not sdkman_init.stat.exists
  become: '{{ sdkman_user != ansible_user_id }}'
  become_user: '{{ sdkman_user }}'
- name: Fix permissions on SDKMAN_DIR
  file:
    path: '{{ sdkman_dir }}'
    state: directory
    owner: '{{ sdkman_user }}'
    group: '{{ sdkman_group }}'
    recurse: true
  become: yes
  tags:
    - sdkman_privilege